### ISSUE TITLE
Use specific, platform-independent data types

### ISSUE THREAD

**Issue by NePoCz** [muety/telepush#40]
Hi, I build my own docker image for Raspberry Pi (armhf) using your repo. I needed to make one small change in Dockerfile (add one line - RUN apk add git - so should not change anything). The build was fine, but after starting the container and starting a chat with my bot, I get the following error (of course, ID changed): 

`2022/04/14 12:19:19 error getting updates: json: cannot unmarshal number 1234567890 into Go struct field TelegramUser.result.message.from.id of type int`

Any idea what might be wrong? Could it be connected to a different arch?

**Comment by muety** [comment]
Hi @NePoCz, thanks for bringing this up. I assume you redacted the actual chat ID number and it's not actually 1234567890, is it? I assume this is a data type issue. According to https://core.telegram.org/bots/api#user, the ID can be 52 bits long. We're using an `int` here, which, on a 32-bit platform like `armhf`, will be an `int32` in fact. Can you confirm your real chat ID is higher than 4294967295 or lower than -4294967295?

**Comment by NePoCz** [comment]
Thanks for the quick response and fix. I built the image again with the patch included and now everything works fine. Yes my chat ID is out of the int32 range (5358xxxxxx), so that must have been the cause.

**Comment by muety** [comment]
Great to hear! I'm glad everything's working again.

**Comment by NePoCz** [comment]
By the way, I have been using it for a while now and so far no problems on armhf. Any plans to build the docker image for other platforms (e.g. armhf/arm64)? I dont want to set up a separate issue for this, so just curiously asking here

**Comment by muety** [comment]
If people need images for different CPU architectures just open a new ticket and someone (maybe myself) will jump onto it, hopefully :)
