### ISSUE TITLE
High-entropy tokens.

### ISSUE THREAD

**Issue by vi** [muety/telepush#41]
I tried to start `TelepushBot` and it issued me a token that consist of just six hex characters.
Does it mean that one can guess the token or just annoy random people by sending random messages though TelepushBot?
Should TelepushBot issue longer, more random tokens?

**Comment by muety** [comment]
Hi @vi, thanks for your comment. Yes, the tokens are indeed only 6-character random strings. However, since there are 2.17 * 10⁹  possible permutations, I consider the probability of guessing a correct token to annoy people still fairly low.
