### ISSUE TITLE
failed to read store from /srv/data/store.gob

### ISSUE THREAD

**Issue by pastukhov** [muety/telepush#51]
Hi!
I'm getting this error when run telepush with docker:
```
docker run --rm \
        -p 8080:8080 \
        -v /opt/telepush:/srv \
        --name telepush \
        telepush \
        -mode webhook \
        -token my-token \
        -metrics \
        -dataDir /srv/data \
        -urlSecret secret \
        -whitelist /srv/whitelist.txt
```
any advice?

**Comment by pastukhov** [comment]
Permission on /opt/telepush is 777 and "data" folder is created while telepush start

**Comment by muety** [comment]
I think the problem is that the bot will look for its data directory at `/srv/data`, but your mountpoint is only at `/srv` and it won't create the sub directory itself. So if you mount your volume directly to `/srv/data`, the issue might be resolved. Otherwise I can have a deeper look tomorrow.

**Comment by pastukhov** [comment]
Yep, with 
```
docker run --rm \
        -p 8880:8080 \
        -v /opt/telepush/data:/srv/data \
        -v /opt/telepush/config:/srv/config \
        --name %n \
        ghcr.io/muety/telepush \
        -mode webhook \
        -token token\
        -metrics \
        -dataDir /srv/data \
        -urlSecret secret \
        -whitelist /srv/config/whitelist.txt
``` 
it is working well. Thanks!
